<?php

/**
 * @category  Scandiweb
 * @copyright Copyright (c) 2024 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
// use Scandiweb\MenuOrganizer\ViewModel\MenuManager;
use Hyva\Theme\ViewModel\Navigation;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$uniqueId = '_' . uniqid();

// Menu manager from Scandiweb
// /** @var MenuManager $viewModelMenuManager */
// $viewModelMenuManager = $viewModels->require(MenuManager::class);
// $menuItems = $viewModelMenuManager->getMenuItems('menu');
// $block->setData('cache_tags', $viewModelMenuManager->getIdentities());

// Default navigation
/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>
<script>
    'use strict';

    const initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            mobilePanelActiveId: null,
            mobilePanelActiveItemStack: [],
            open: false,

            openMenu() {
                this.open = true
                this.$nextTick(() => hyva.trapFocus(this.$refs['mobileMenuNavLinks']));
                // Prevent from body scrolling while mobile menu opened
                document.body.style.overflow = 'hidden';
            },
            closeMenu() {
                document.body.style.overflow = '';

                if (this.open) {
                    this.$nextTick(() => this.$refs['mobileMenuTrigger'].focus() || hyva.releaseFocus());
                }

                this.open = false
                setTimeout(() => this.mobilePanelActiveItemStack = [], 300);
            },
            openSubcategory(index) {
                const menuNodeRef = document.querySelector('[data-child-id=' + `"${index}"` + ']')
                this.mobilePanelActiveId = this.mobilePanelActiveId === index ? 0 : index
                this.$nextTick(() => hyva.trapFocus(menuNodeRef))
            },
            backToMainCategories(index) {
                const menuNodeRef = document.querySelector('[data-child-id=' + `"${index}"` + ']')
                this.mobilePanelActiveId = 0
                this.$nextTick(() => {
                    hyva.trapFocus(this.$refs['mobileMenuNavLinks'])
                    menuNodeRef.querySelector('a').focus()
                })
            }
        }
    }
</script>
<nav
    x-data="initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?>()"
    @keydown.window.escape="closeMenu()"
    class="z-30 navigation lg:hidden"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation')) ?>"
    role="navigation">
    <!-- mobile -->
    <button
        x-ref="mobileMenuTrigger"
        @click="openMenu()"
        class="block"
        :class="{ 'overflow-x-hidden overflow-y-auto fixed top-0 left-0 w-full': open }"
        type="button"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Open menu')) ?>"
        aria-haspopup="menu"
        :aria-expanded="open"
        :hidden="open">
        <?= $heroicons->menuHtml('', 24, 24, [":class" => "{ 'hidden' : open, 'block': !open }", "aria-hidden" => "true"]) ?>
    </button>
    <div
        x-ref="mobileMenuNavLinks"
        class="
            fixed top-0 right-0 w-full h-full p-1 hidden
            flex-col border-t border-container bg-container-lighter
            overflow-y-auto overflow-x-hidden
        "
        :class="{ 'flex': true, 'hidden': false }"
        x-show="open"
        x-transition:enter="transform transition ease-in-out duration-300 sm:duration-500"
        x-transition:enter-start="translate-x-[-100%]"
        x-transition:enter-end="translate-x-0"
        x-transition:leave="transform transition ease-in-out duration-300 sm:duration-500"
        x-transition:leave-start="translate-x-0"
        x-transition:leave-end="translate-x-[-100%]"
        :aria-hidden="open ? 'false' : 'true'"
        role="dialog"
        aria-modal="true">
        <ul
            class="border-t flex flex-col gap-y-1 mt-16"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation links')) ?>">
            <?php foreach ($menuItems as $index => $itemLevel1): ?>
                <li
                    data-child-id="<?= $escaper->escapeHtmLAttr($index) ?>-main"
                    class="level-0">
                    <div
                        class="flex items-center transition-transform duration-150 ease-in-out transform"
                        :class="{
                            '-translate-x-full' : mobilePanelActiveId,
                            'translate-x-0' : !mobilePanelActiveId
                        }">
                        <a
                            class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                bg-container-lighter border-container level-0
                            "
                            href="<?= $escaper->escapeUrl($itemLevel1['url']) ?>"
                            title="<?= $escaper->escapeHtmlAttr($itemLevel1['name']) ?>">
                            <?= $escaper->escapeHtml($itemLevel1['name']) ?>
                        </a>
                        <?php if (!empty($itemLevel1['childData'])): ?>
                            <button
                                @click="
                                    mobilePanelActiveItemStack.push('<?= $escaper->escapeHtmlAttr($index); ?>')
                                "
                                class="absolute right-0 flex items-center justify-center w-11 h-11 mr-8 cursor-pointer
                                    bg-container-lighter border-container"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Open %1 subcategories', $itemLevel1['name'])) ?>"
                                aria-haspopup="true"
                                :aria-expanded="mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>'">
                                <div class="w-8 h-8 border rounded">
                                    <?= $heroicons->chevronRightHtml('w-full h-full p-1', 24, 24, ["aria-hidden" => "true"]) ?>
                                </div>
                            </button>
                        <?php endif; ?>
                    </div>
                    <?php if (!empty($itemLevel1['childData'])): ?>
                        <div
                            data-child-id="<?= $escaper->escapeHtmLAttr($index) ?>"
                            class="absolute top-0 right-0 z-10 flex flex-col gap-1 w-full h-full p-1 bg-container-lighter transition-transform duration-300"
                            :class="{
                                        'translate-x-full' : !mobilePanelActiveItemStack.includes('<?= $escaper->escapeHtmlAttr($index); ?>'),
                                        'translate-x-0' : mobilePanelActiveItemStack.includes('<?= $escaper->escapeHtmlAttr($index); ?>'),
                                }">
                            <ul
                                class="mt-16"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Subcategories')) ?>">
                                <li>
                                    <button
                                        type="button"
                                        class="flex items-center px-8 py-4 border-b cursor-pointer bg-container border-container w-full border-t"
                                        @click="mobilePanelActiveItemStack.pop()"
                                        aria-label="<?= $escaper->escapeHtmlAttr(__('Back to main categories')) ?>">
                                        <?= $heroicons->chevronLeftHtml('', 24, 24, ["aria-hidden" => "true"]); ?>
                                        <span class="ml-4">
                                            <?= $escaper->escapeHtml($itemLevel1['name']) ?>
                                        </span>
                                    </button>
                                </li>
                                <li>
                                    <a
                                        href="<?= $escaper->escapeUrl($itemLevel1['url']) ?>"
                                        title="<?= $escaper->escapeHtmlAttr($itemLevel1['name']) ?>"
                                        class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                            bg-container-lighter border-container
                                        ">
                                        <span>
                                            <?= $escaper->escapeHtml(__('View All')) ?>
                                        </span>
                                    </a>
                                </li>
                                <?php foreach ($itemLevel1['childData'] as $level2Index => $itemLevel2): ?>
                                        <li
                                            data-child-id="<?= $escaper->escapeHtmLAttr($index) ?>-main"
                                            class="level-0">
                                            <div
                                                class="flex items-center transition-transform duration-150 ease-in-out transform"
                                                :class="{
                                                    '-translate-x-full' : mobilePanelActiveId,
                                                    'translate-x-0' : !mobilePanelActiveId
                                                }">
                                                <a
                                                    class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                                        bg-container-lighter border-container level-0
                                                    "
                                                    href="<?= $escaper->escapeUrl($itemLevel2['url']) ?>"
                                                    title="<?= $escaper->escapeHtmlAttr($itemLevel2['name']) ?>">
                                                    <?= $escaper->escapeHtml($itemLevel2['name']) ?>
                                                </a>
                                                <?php if (!empty($itemLevel2['childData'])): ?>
                                                    <button
                                                        @click="
                                                            mobilePanelActiveItemStack.push('<?= $escaper->escapeHtmlAttr($level2Index); ?>')
                                                        "
                                                        class="absolute right-0 flex items-center justify-center w-11 h-11 mr-8 cursor-pointer
                                                            bg-container-lighter border-container"
                                                        aria-label="<?= $escaper->escapeHtmlAttr(__('Open %1 subcategories', $itemLevel1['name'])) ?>"
                                                        aria-haspopup="true"
                                                        :aria-expanded="mobilePanelActiveId === '<?= /* @noEscape */ (string) $level2Index ?>'">
                                                        <div class="w-8 h-8 border rounded">
                                                            <?= $heroicons->chevronRightHtml('w-full h-full p-1', 24, 24, ["aria-hidden" => "true"]) ?>
                                                        </div>
                                                    </button>
                                                <?php endif; ?>
                                            </div>
                                            <?php if (!empty($itemLevel2['childData'])): ?>
                                                <div
                                                    data-child-id="<?= $escaper->escapeHtmLAttr($level2Index) ?>"
                                                    class="absolute top-0 right-0 z-10 flex flex-col gap-1 w-full h-full p-1 bg-container-lighter transition-transform duration-300"
                                                    :class="{
                                                                'translate-x-full' : !mobilePanelActiveItemStack.includes('<?= $escaper->escapeHtmlAttr($level2Index); ?>'),
                                                                'translate-x-0' : mobilePanelActiveItemStack.includes('<?= $escaper->escapeHtmlAttr($level2Index); ?>'),
                                                        }">
                                                        <ul
                                                            class="mt-16"
                                                            aria-label="<?= $escaper->escapeHtmlAttr(__('Subcategories')) ?>">
                                                            <li>
                                                                <button
                                                                    type="button"
                                                                    class="flex items-center px-8 py-4 border-b cursor-pointer bg-container border-container w-full border-t"
                                                                    @click="mobilePanelActiveItemStack.pop()"
                                                                    aria-label="<?= $escaper->escapeHtmlAttr(__('Back to main categories')) ?>">
                                                                    <?= $heroicons->chevronLeftHtml('', 24, 24, ["aria-hidden" => "true"]); ?>
                                                                    <span class="ml-4">
                                                                        <?= $escaper->escapeHtml($itemLevel2['name']) ?>
                                                                    </span>
                                                                </button>
                                                            </li>
                                                            <li>
                                                                <a
                                                                    href="<?= $escaper->escapeUrl($itemLevel1['url']) ?>"
                                                                    title="<?= $escaper->escapeHtmlAttr($itemLevel1['name']) ?>"
                                                                    class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                                                        bg-container-lighter border-container
                                                                    ">
                                                                    <span>
                                                                        <?= $escaper->escapeHtml(__('View All')) ?>
                                                                    </span>
                                                                </a>
                                                            </li>
                                                            <?php foreach ($itemLevel2['childData'] as $level3Index => $itemLevel3): ?>
                                                                <li>
                                                                    <a
                                                                        class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                                                            bg-container-lighter border-container level-0
                                                                        "
                                                                        href="<?= $escaper->escapeUrl($itemLevel3['url']) ?>"
                                                                        title="<?= $escaper->escapeHtmlAttr($itemLevel3['name']) ?>">
                                                                        <?= $escaper->escapeHtml($itemLevel3['name']) ?>
                                                                    </a>
                                                                </li>
                                                            <?php endforeach; ?>
                                                        </ul>
                                                </div>
                                            <?php endif; ?>
                                        </li>
                                <?php endforeach; ?>
                            </ul>
                            <button
                                @click="closeMenu()"
                                class="absolute flex justify-end w-16 self-end mb-1 transition-none"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>">
                                <?= $heroicons->xHtml('hidden p-4', 64, 64, [":class" => "{ 'hidden' : !open, 'block': open }", "aria-hidden" => "true"]) ?>
                            </button>
                        </div>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <button
            @click="closeMenu()"
            class="absolute flex justify-end w-16 self-end mb-1"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
            type="button">
            <?= $heroicons->xHtml('hidden p-4', 64, 64, [":class" => "{ 'hidden' : !open, 'block': open }", "aria-hidden" => "true"]) ?>
        </button>
    </div>
</nav>