<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_StyleGuide
 * @author    Aleksandrs Kondratjevs <info@scandiweb.com>
 * @copyright Copyright (c) 2024 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

/** @var \Scandiweb\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div class="flex flex-wrap gap-4">
    <div class="bg-primary text-white p-4 w-32 flex flex-col gap-3">
        <div class="flex flex-col">
            <span class="h-14">Primary</span>
        </div>
        <span>#1D4ED8</span>
    </div>
    <div class="bg-secondary text-white p-4 w-32 flex flex-col gap-3">
        <div class="flex flex-col">
            <span class="h-14">Secondary</span>
        </div>
        <span>#BFDBFE</span>
    </div>
</div>