<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @author    Aleksandrs Kondratjevs <info@scandiweb.com>
 * @copyright Copyright (c) 2024 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

// Content
$title = $block->getContentTitle();
$description = $block->getContentDescription();

// First CTA configurations
$isShowFirstCta = $block->getShowFirstCta();
$firstCtaText = $block->getFirstCtaText();
$firstCtaClasses = $block->getFirstCtaType();
$firstCtaLink = $block->getFirstCtaLink();

// Second CTA configurations
$isShowSecondCta = $block->getShowSecondCta();
$secondCtaText = $block->getSecondCtaText();
$secondCtaClasses = $block->getSecondCtaType();
$secondCtaLink = $block->getSecondCtaLink();

// Visual
$isVisualOnLeft = $block->getVisualContentPosition() === 'left';
$visualType = $block->getVisualType();
$image = $block->getImage($visualType);
$videoUrl = $block->getVisualContentVid();
$placeHolderType = '';

//Visual Type Conditional Statements
$isImageExist = $visualType === 'image' && $image;
$isVideoExist = $visualType === 'video' && $videoUrl;

if ($isVideoExist) {
    $placeHolderType = $block->getPlaceholderType();
    $imagePlaceholder = $placeHolderType === 'uploader' ?
        $image['url'] : $block->getVisualContentVideoPlaceholderUrl();
}

//Jaralax URLs
$jarallaxUrl = $block->getViewFileUrl('Magento_PageBuilder::js/jarallax.min.js');
$jarallaxVideoUrl = $block->getViewFileUrl('Magento_PageBuilder::js/jarallax-video.min.js');
$jarallaxCssUrl = $block->getViewFileUrl('Scandiweb_ContentTypes::css/jarallax.min.css');

?>
<div class="flex flex-col md:flex-row gap-4">
    <?php if ($isImageExist || $isVideoExist): ?>
        <div class="w-full <?= $isVideoExist ? 'h-96' : '' ?> <?= $isVisualOnLeft ? '' : 'order-2' ?>">
            <?php if ($visualType === 'image'): ?>
                <img src="<?= $escaper->escapeUrl($image['url']) ?>" alt="<?= $escaper->escapeHtmlAttr($image['alt']) ?>">
                </img>
            <?php else: ?>
                <div class="jarallax overflow-hidden h-full" data-video-src="<?= $escaper->escapeUrl($videoUrl) ?>">
                    <img class="jarallax-placeholder" src="<?= $escaper->escapeUrl($imagePlaceholder) ?>" alt="<?= $escaper->escapeHtmlAttr($image['alt']) ?>">
                    </img>
                </div>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <div class="flex flex-col gap-4 w-full h-full my-auto justify-center <?= ($isImageExist || $isVideoExist) ? '' : 'items-center' ?>">
        <?php if ($title): ?>
            <?= html_entity_decode($title) ?>
        <?php endif; ?>
        <?php if ($description): ?>
            <?= html_entity_decode($description) ?>
        <?php endif; ?>
        <div class="flex gap-4">
            <?php if ($isShowFirstCta === 'show'): ?>
                <a href="<?= $escaper->escapeHtmlAttr($firstCtaLink) ?>" class="<?= $firstCtaClasses ?>"><?= $escaper->escapeHtml($firstCtaText) ?></a>
            <?php endif; ?>
            <?php if ($isShowSecondCta === 'show'): ?>
                <a href="<?= $escaper->escapeHtmlAttr($secondCtaLink) ?>" class="<?= $secondCtaClasses ?>"><?= $escaper->escapeHtml($secondCtaText) ?></a>
            <?php endif; ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    window.addEventListener('DOMContentLoaded', function() {
        const jarallaxCssUrl = '<?= $escaper->escapeJs($escaper->escapeUrl($jarallaxCssUrl)) ?>';
        const jarallaxUrl = '<?= $escaper->escapeJs($escaper->escapeUrl($jarallaxUrl)) ?>';
        const jarallaxVideoUrl = '<?= $escaper->escapeJs($escaper->escapeUrl($jarallaxVideoUrl)) ?>';

        function loadCss(url) {
            const link = document.createElement('link');
            link.rel = 'stylesheet';
            link.href = url;
            document.head.appendChild(link);
        }

        function loadScript(url, callback) {
            let script = document.createElement('script');
            script.type = 'text/javascript';
            script.src = url;
            script.onload = callback;
            document.body.appendChild(script);
        }

        loadScript(jarallaxUrl, () => {
            loadScript(jarallaxVideoUrl, () =>{
                let elements = document.querySelectorAll(".jarallax");

                elements.forEach(element => {
                    jarallax(element);

                    let placeholders = document.querySelectorAll('.jarallax-placeholder');

                    placeholders.forEach(placeholder => {
                        placeholder.style.display = 'none';
                    });
                });
            });
        });
    });
</script>
